//using System;
//using System.CodeDom.Compiler;
//using System.ComponentModel;
//using System.Diagnostics;
//using System.Drawing;
//using System.Globalization;
//using System.Resources;
//using System.Runtime.CompilerServices;
//namespace MCFaceRecognitionVideo.Properties
//{
//	//[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), DebuggerNonUserCode, CompilerGenerated]
//	internal class Resources
//	{
//        private static System.ComponentModel.ComponentResourceManager resources1 = new System.ComponentModel.ComponentResourceManager(typeof(Resources));
//        //private static ResourceManager resourceMan;
//		private static CultureInfo resourceCulture;
//		[EditorBrowsable(EditorBrowsableState.Advanced)]
//		//internal static ResourceManager ResourceManager
//		//{
//		//	get
//		//	{
//		//		if (Resources.resourceMan == null)
//		//		{
//		//			Resources.resourceMan = new ResourceManager("MCFaceRecognitionVideo.Properties.Resources", typeof(Resources).Assembly);

//  //              }
//		//		return Resources.resourceMan;
//		//	}
//		//}

//        internal static ResourceManager ResourceManager
//        {
//            get
//            {
//                if (Resources.resources1 == null)
//                {
//                    resources1 = new System.ComponentModel.ComponentResourceManager(typeof(MCFaceRecognitionVideo.Properties.Resources));
//                }
//                return Resources.resources1;
//            }
//        }
//        [EditorBrowsable(EditorBrowsableState.Advanced)]
//		internal static CultureInfo Culture
//		{
//			get
//			{
//				return Resources.resourceCulture;
//			}
//			set
//			{
//				Resources.resourceCulture = value;
//			}
//		}
//        //internal static Bitmap top_bg
//        //{
//        //	get
//        //	{
//        //		return (Bitmap)Resources.ResourceManager.GetObject("top_bg", Resources.resourceCulture);
//        //	}
//        //}
//        //internal static Bitmap weiqiyong
//        //{
//        //	get
//        //	{
//        //		return (Bitmap)Resources.ResourceManager.GetObject("weiqiyong", Resources.resourceCulture);
//        //	}
//        //}
//        //internal static Bitmap zanwuzhaopian
//        //{
//        //	get
//        //	{
//        //		return (Bitmap)Resources.ResourceManager.GetObject("zanwuzhaopian", Resources.resourceCulture);
//        //	}
//        //}
//        //internal static Bitmap 分页_上一页
//        //{
//        //	get
//        //	{
//        //		return (Bitmap)Resources.ResourceManager.GetObject("分页_上一页", Resources.resourceCulture);
//        //	}
//        //}
//        //internal static Bitmap 分页_下一页
//        //{
//        //	get
//        //	{
//        //		return (Bitmap)Resources.ResourceManager.GetObject("分页_下一页", Resources.resourceCulture);
//        //	}
//        //}
//        //internal static Bitmap 分页_最前页
//        //{
//        //	get
//        //	{
//        //		return (Bitmap)Resources.ResourceManager.GetObject("分页_最前页", Resources.resourceCulture);
//        //	}
//        //}
//        //internal static Bitmap 分页_最后页
//        //{
//        //	get
//        //	{
//        //		return (Bitmap)Resources.ResourceManager.GetObject("分页_最后页", Resources.resourceCulture);
//        //	}
//        //}

//        internal static Bitmap top_bg
//        {
//            get
//            {
//                return (Bitmap)resources1.GetObject("top_bg");
//            }
//        }
//        internal static Bitmap weiqiyong
//        {
//            get
//            {
//                return (Bitmap)resources1.GetObject("weiqiyong");
//            }
//        }
//        internal static Bitmap zanwuzhaopian
//        {
//            get
//            {
//                return (Bitmap)resources1.GetObject("zanwuzhaopian");
//            }
//        }
//        internal static Bitmap 分页_上一页
//        {
//            get
//            {
//                return (Bitmap)resources1.GetObject("分页_上一页");
//            }
//        }
//        internal static Bitmap 分页_下一页
//        {
//            get
//            {
//                return (Bitmap)resources1.GetObject("分页_下一页");
//            }
//        }
//        internal static Bitmap 分页_最前页
//        {
//            get
//            {
//                return (Bitmap)resources1.GetObject("分页_最前页");
//            }
//        }
//        internal static Bitmap 分页_最后页
//        {
//            get
//            {
//                return (Bitmap)resources1.GetObject("分页_最后页");
//            }
//        }


//        internal Resources()
//		{
//		}
//	}
//}

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCFaceRecognitionVideo.Properties
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCFaceRecognitionVideo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap top_bg
        {
            get
            {
                object obj = ResourceManager.GetObject("top_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap weiqiyong
        {
            get
            {
                object obj = ResourceManager.GetObject("weiqiyong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zanwuzhaopian
        {
            get
            {
                object obj = ResourceManager.GetObject("zanwuzhaopian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 分页_上一页
        {
            get
            {
                object obj = ResourceManager.GetObject("分页_上一页", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 分页_下一页
        {
            get
            {
                object obj = ResourceManager.GetObject("分页_下一页", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 分页_最前页
        {
            get
            {
                object obj = ResourceManager.GetObject("分页_最前页", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 分页_最后页
        {
            get
            {
                object obj = ResourceManager.GetObject("分页_最后页", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}

